#@package _global_
defaults:
  - _self_
  - datasets/lidc
  - tasks/threshold

base_path: "/home/kckahl/LIDC-IDRI/ActiveLearning/FirstCycle"
second_cycle_path: "/home/kckahl/LIDC-IDRI/ActiveLearning/SecondCycle"
experiments:
  - ${LIDC}

tasks: ["threshold"]

task_params:
  threshold: ${THRESHOLD}
  aggregation:
    datasets: ["id", "ood", "unlabeled", "val"]

