#@package _global_
defaults:
  - _self_
  - datasets/lidc
  - tasks/threshold
  - tasks/aggregation_patch_thresh

base_path: "/home/kckahl/LIDC-IDRI/ActiveLearning/FirstCycle"
second_cycle_path: "/home/kckahl/LIDC-IDRI/ActiveLearning/SecondCycle"
experiments:
  - ${LIDC}

tasks: ["aggregation"]

task_params:
  threshold:
    - ${QUANTILE}
    - ${THRESHOLD}
  aggregation: ${AGG_PATCH_THRESH}

