defaults:
  - _self_
  - datasets/gta
  - tasks/aggregation_patch_image
  - tasks/failure_detection

base_path: "/nvme/GTA/Experiments/FirstCycle"
second_cycle_path: "/nvme/GTA/Experiments/SecondCycle"
experiments:
  - ${GTA}

tasks: ["al_improvement"]

task_params:
  aggregation: ${AGG_PATCH_IMAGE}
  second_cycle_splits:
    datasets: ["unlabeled"]
    function:
      _target_: evaluation.split_file_generation.split_files_second_cycle.generate_split_file
      base_splits_path: "/nvme/GTA/splits/"
  second_cycle_splits_random:
    datasets: [ "unlabeled" ]
    function:
      _target_: evaluation.split_file_generation.split_files_second_cycle_random.generate_split_file
      base_splits_path: "/nvme/GTA/splits/"
      random_types: [ "random" ]
  ood_detection:
    datasets: [ "unlabeled" ]
    function:
      _target_: evaluation.metrics.auroc.ood_detection
      base_splits_path: "/nvme/GTA/splits/"
  failure_detection: ${FAILURE_DETECTION}
  calibration:
    datasets: ["id", "ood"]
    function:
      _target_: evaluation.metrics.ace.main
      ignore_value: 255
  ambiguity_modeling:
    datasets: [ "id", "ood" ]
    function:
      _target_: evaluation.metrics.ncc.main
  al_improvement:
    datasets: [ "ood" ]
    function:
      _target_: evaluation.metrics.al_improvement.main