defaults:
  - _self_
  - eval_default_config
  - tasks/threshold.yaml
  - datasets/toy
  - datasets/toy_seed123
base_path: "/home/kckahl/Uncertainty/ToyExperimentOOD/AleatoricTrain"
experiments:
  - ${TOY}
  - ${TOY_SEED123}

tasks: ["threshold"]

task_params:
  threshold: ${THRESHOLD}
  aggregation:
    datasets: ["id", "ood", "unlabeled", "val"]
