defaults:
  - _self_
  - eval_config_toy
experiments:
  iter_params:
    seed: ["123"]

prediction_models:
  Softmax:
    naming_scheme_version: "epochs{epochs}"
  Dropout:
    naming_scheme_version: "epochs{epochs}"
  Ensemble:
    naming_scheme_version: "epochs{epochs}_fold{fold}"
  TTA:
    naming_scheme_version: "epochs{epochs}"
  SSN:
    naming_scheme_version: "epochs{epochs}_rank{rank}_pretrain{pretrain}"
