defaults:
  - _self_
  - datasets/gta
  - tasks/aggregation_patch_image
base_path: "/nvme/GTA/Experiments/FirstCycle"
second_cycle_path: "/nvme/GTA/Experiments/SecondCycle"
experiments:
  - ${GTA}

tasks: ["aggregation"]

task_params:
  aggregation: ${AGG_PATCH_IMAGE}