defaults:
  - _self_
  - datasets/toy
  - datasets/toy_seed123
  - tasks/threshold

base_path: "/home/kckahl/Uncertainty/ToyExperimentOOD/AleatoricTrain"
experiments:
  - ${TOY}
  - ${TOY_SEED123}

tasks: ["threshold"]

task_params:
  threshold:
  - ${QUANTILE}
  - ${THRESHOLD}
  aggregation:
    datasets: ["id", "ood", "unlabeled", "val"]
