defaults:
  - _self_
  - datasets/toy
  - datasets/toy_seed123
  - tasks/threshold
  - tasks/aggregation_patch_thresh

base_path: "/home/kckahl/Uncertainty/ToyExperimentOOD/AleatoricTrain"
experiments:
  - ${TOY}
  - ${TOY_SEED123}

tasks: ["aggregation"]

task_params:
  threshold:
  - ${QUANTILE}
  - ${THRESHOLD}
  aggregation: ${AGG_PATCH_THRESH}
