_target_: uncertainty_modeling.data.torch_dataloader.BaseDataModule   # Base Data Module
num_classes: 24
ignore_index: 255
num_workers: 10      # Parsing all needed experiment
batch_size: 6
val_batch_size: 6
data_fold_id: 0
dataset:
  _target_: uncertainty_modeling.data.cityscapes_dataset.Cityscapes_dataset
  splits_path: "/nvme/GTA/splits/cityscapes/splits.pkl"