_target_: uncertainty_modeling.data.gta_datamodule.GTADataModule
num_classes: 25
data_fold_id: 0
batch_size: 8
num_workers: 8
splits_path: "/home/kckahl/E130-Personal/Kahl/GTA/splits/firstCycle/splits.pkl"