_target_: uncertainty_modeling.lidc_idri_datamodule_3D.LidcIdriDataModule3D
shift_feature: "texture"
num_raters: 4
data_num_folds: 5
data_fold_id: 0
batch_size: 8
patch_size: 64
patch_overlap: 1
num_workers: 8
splits_path: "/home/${oc.env:USER}/LIDC-IDRI/CroppedData/splits_texture.pkl"
