#@package _global_
defaults:
  - datamodule: gta_torch_config
  - model: hrnet_config
exp_name: "Softmax-Debug"
version: null
data_input_dir: "/nvme/GTA"
save_dir: "/nvme/GTA"
seed: 123
max_epochs: 300
batch_size: 6
# same as in semantic segmentation repo
learning_rate: 0.01
weight_decay: 0.0005
gpus: '1'
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${save_dir}
  name: ${exp_name}
progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 10