defaults:
  - datamodule: gta_config
  - model: hrnet_config
exp_name: "Softmax-Debug"
version: null
data_input_dir: "/home/kckahl/E130-Personal/Kahl/GTA"
save_dir: "/home/kckahl/E130-Personal/Kahl/GTA/DownstreamTasks"
seed: 123
max_epochs: 50
batch_size: 8
learning_rate: 3.0e-4
weight_decay: 10.0e-6
gpus: '1'
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${save_dir}
  name: ${exp_name}
progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 10