defaults:
  - datamodule: case1_config
  - model: unet3D_config
exp_name: "Softmax-Case-1"
version: null
data_input_dir: "/home/${oc.env:USER}/Uncertainty/ToyData"
save_dir: "/home/${oc.env:USER}/Uncertainty/ToyExperiments"
seed: 123
max_epochs: 50
batch_size: 8
learning_rate: 3.0e-4
weight_decay: 10.0e-6
gpus: '1'
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${save_dir}
  name: ${exp_name}
progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 10