defaults:
  - datamodule: case1_config
  - model: ssn_unet3D_config
exp_name: "SSN-Case-1"
version: "tanh_lowScale_mask_ceLoss"
data_input_dir: "/media/kahl/Data/Uncertainty/ToyData"
save_dir: "/media/kahl/Data/Uncertainty/ToyExperiment"
seed: 123
max_epochs: 5
batch_size: 8
learning_rate: 3.0e-4
weight_decay: 10.0e-6
aleatoric_loss: null
n_aleatoric_samples: 10
gpus: '1'
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${save_dir}
  name: ${exp_name}
progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 10