#@package _global_
seg_performance:
  dice:
    metrics_file_name: "metrics.json"
    metrics_key: "dice"
    dataset_splits: ["id", "ood"]
    levels: ["pred_model"]
    higher_better: True
ood_detection:
  auroc:
    metrics_file_name: "ood_detection.json"
    metrics_key: "auroc"
    dataset_splits: null
    levels: ["pred_model", "unc_type", "aggregation"]
    higher_better: true
failure_detection:
  aurc:
    metrics_file_name: "failure_detection.json"
    metrics_key: "aurc"
    dataset_splits: ["id", "ood"]
    levels: ["pred_model", "unc_type", "aggregation"]
    higher_better: false
  eaurc:
    metrics_file_name: "failure_detection.json"
    metrics_key: "eaurc"
    dataset_splits: ["id", "ood"]
    levels: ["pred_model", "unc_type", "aggregation"]
    higher_better: false
active_learning:
  al_improvement:
    metrics_file_name: "al_improvement.json"
    metrics_key: "al_improvement"
    dataset_splits: ["ood"]
    levels: ["pred_model", "unc_type", "aggregation"]
    higher_better: true
calibration:
  ace:
    metrics_file_name: "calibration.json"
    metrics_key: "ace"
    dataset_splits: ["id", "ood"]
    levels: ["pred_model", "unc_type"]
    higher_better: false
ambiguity_modeling:
  ncc:
    metrics_file_name: "ambiguity_modeling.json"
    metrics_key: "ncc"
    dataset_splits: ["id", "ood"]
    levels: ["pred_model", "unc_type"]
    higher_better: true
  ged:
    metrics_file_name: "metrics.json"
    metrics_key: "ged"
    dataset_splits: ["id", "ood"]
    levels: ["pred_model"]
    higher_better: false