################################################################################################
##############################            LOGGING           ####################################
################################################################################################
exp_name:                     "Heart-Segmentation-Test"
save_dir:                     "/home/kahl/Documents/SSL-SEG/experiments/debug"
progress_bar_refresh_rate:    10
profiler:                     True


################################################################################################
##############################       PRETEXT TRAINING       ####################################
################################################################################################
seed:                         123
max_epochs:                   50
batch_size:                   16
learning_rate:                3.0e-4
weight_decay:                 10.0e-6
precision:                    32
gpus:                         '1'

################################################################################################
##############################     DATASET / DATALOADER     ####################################
################################################################################################
data_input_dir:               "/home/kahl/Documents/Datasets/Heart"
data_num_folds:               5
data_fold_id:                 0
dataloader_workers:           12

################################################################################################
##############################           DATAMODULE         ####################################
################################################################################################
datamodule_module_name:       "heart_datamodule"
datamodule_class_name:        "HeartDataModule"

################################################################################################
##############################          ARCHITECTURE        ####################################
################################################################################################
