################################################################################################
##############################            LOGGING           ####################################
################################################################################################
exp_name: "Toy-Data-Test"
save_dir: "/home/kahl/Documents/ToyExperiment"
progress_bar_refresh_rate: 10
profiler: True


################################################################################################
##############################       PRETEXT TRAINING       ####################################
################################################################################################
seed: 123
max_epochs: 2
batch_size: 8
learning_rate: 3.0e-4
weight_decay: 10.0e-6
precision: 32
gpus: '1'

################################################################################################
##############################     DATASET / DATALOADER     ####################################
################################################################################################
dataset_name: "Case_1"
num_raters: 3
data_input_dir: "/home/kahl/Documents/ToyData"
data_num_folds: 5
data_fold_id: 0
dataloader_workers: 12

################################################################################################
##############################           DATAMODULE         ####################################
################################################################################################
datamodule_module_name: "toy_datamodule_3D"
datamodule_class_name: "ToyDataModule3D"

################################################################################################
##############################          ARCHITECTURE        ####################################
################################################################################################
