#@package _global_
defaults:
  - /../../uncertainty_modeling/configs/datamodule/gta_torch_config@GTA.datamodule_config
  - /../../uncertainty_modeling/configs/data_augmentations/tta_augmentations
  - _self_

AUGMENTATIONS:
  TEST:
    - Compose:
        transforms:
          - Normalize:
              mean: ${AUGMENTATIONS.mean}
              std: ${AUGMENTATIONS.std}
          - StochasticLabelSwitches:
              always_apply: True
              p: 1.0
              n_reference_samples: ${GTA.n_reference_segs}
          - ToTensorV2:

GTA:
  iter_params:
    pred_model: [ "Softmax", "Dropout-Final", "Ensemble", "TTA", "SSN" ]
    seed: [ "123", "124", "125" ]
  fold: 0
  rank: 10
  n_classes: 19
  image_ending: ".png"
  unc_ending: ".tif"
  datamodule_config:
    data_input_dir: "/nvme/GTA"
  n_reference_segs: 5
  pred_seg_loading:
    _target_: evaluation.utils.gta.pred_seg_loading
  gt_unc_map_loading:
    _target_: evaluation.utils.gta.gt_unc_map

  prediction_models:
    Softmax:
      naming_scheme_version: "fold{fold}_seed{seed}"
      unc_types: [ "predictive_uncertainty" ]
      aggregations: [ "image_level", "patch_level" ]
    Dropout-Final:
      naming_scheme_version: "fold{fold}_seed{seed}"
      unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
      aggregations: [ "image_level", "patch_level" ]
    Ensemble:
      naming_scheme_version: "fold{fold}_seed{seed}"
      unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
      aggregations: [ "image_level", "patch_level" ]
    TTA:
      naming_scheme_version: "fold{fold}_seed{seed}"
      unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
      aggregations: [ "image_level", "patch_level" ]
    SSN:
      naming_scheme_version: "rank{rank}_fold{fold}_seed{seed}"
      unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
      aggregations: [ "image_level", "patch_level" ]