iter_params:
  pred_model: [ "Softmax", "Dropout", "Ensemble", "TTA", "SSN"]
  seed: [ "128", "158" ]
case: 3
fold: 0
epochs: 150
rank: 5
pretrain: 5
image_ending: ".nii.gz"
unc_ending: ".nii.gz"
n_reference_segs: 3

prediction_models:
  Softmax:
    naming_scheme_pred_model: "{pred_model}-Case-{case}"
    naming_scheme_version: "epochs{epochs}_seed{seed}"
    unc_types: ["predictive_uncertainty"]
    aggregations: ["patch_level", "threshold"]
  Dropout:
    naming_scheme_pred_model: "{pred_model}-Case-{case}"
    naming_scheme_version: "epochs{epochs}_seed{seed}"
    unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty"]
    aggregations: ["patch_level", "threshold"]
  Ensemble:
    naming_scheme_pred_model: "{pred_model}-Case-{case}"
    naming_scheme_version: "epochs{epochs}_fold{fold}_seed{seed}"
    unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
    aggregations: ["patch_level", "threshold"]
  TTA:
    naming_scheme_pred_model: "{pred_model}-Case-{case}"
    naming_scheme_version: "epochs{epochs}_seed{seed}"
    unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
    aggregations: ["patch_level", "threshold"]
  SSN:
    naming_scheme_pred_model: "{pred_model}-Case-{case}-gradient-clip"
    naming_scheme_version: "epochs{epochs}_rank{rank}_pretrain{pretrain}_seed{seed}"
    unc_types: [ "predictive_uncertainty", "aleatoric_uncertainty", "epistemic_uncertainty" ]
    aggregations: ["patch_level", "threshold"]