#@package _global_
TOY_SEED123:
  iter_params:
    pred_model: [ "Softmax", "Dropout", "Ensemble", "TTA", "SSN"]
    seed: [ "123" ]
  case: 3
  fold: 0
  epochs: 150
  rank: 5
  pretrain: 5
  image_ending: ".nii.gz"
  unc_ending: ".nii.gz"

  prediction_models:
    Softmax:
      naming_scheme_pred_model: "{pred_model}-Case-{case}"
      naming_scheme_version: "epochs{epochs}"
      unc_types: ["pred_unc"]
      aggregations: ["patch_level", "threshold"]
    Dropout:
      naming_scheme_pred_model: "{pred_model}-Case-{case}"
      naming_scheme_version: "epochs{epochs}"
      unc_types: [ "pred_unc", "aleatoric_unc", "epistemic_unc"]
      aggregations: ["patch_level", "threshold"]
    Ensemble:
      naming_scheme_pred_model: "{pred_model}-Case-{case}"
      naming_scheme_version: "epochs{epochs}_fold{fold}"
      unc_types: [ "pred_unc", "aleatoric_unc", "epistemic_unc" ]
      aggregations: ["patch_level", "threshold"]
    TTA:
      naming_scheme_pred_model: "{pred_model}-Case-{case}"
      naming_scheme_version: "epochs{epochs}"
      unc_types: [ "pred_unc", "aleatoric_unc", "epistemic_unc" ]
      aggregations: ["patch_level", "threshold"]
    SSN:
      naming_scheme_pred_model: "{pred_model}-Case-{case}-gradient-clip"
      naming_scheme_version: "epochs{epochs}_rank{rank}_pretrain{pretrain}"
      unc_types: [ "pred_unc", "aleatoric_unc", "epistemic_unc" ]
      aggregations: ["patch_level", "threshold"]